sources:
  - RobotoSerif.designspace
  - RobotoSerif-Italic.designspace
familyName: Roboto Serif
axisOrder:
  - GRAD
  - opsz
  - wdth
  - wght
  - ital
stat:
  RobotoSerif[GRAD,opsz,wdth,wght].ttf:
  - name: Grade
    tag: GRAD
    values:
    - name: G100
      value: 100
      flags: 2
  - name: Optical Size
    tag: opsz
    values:
    - name: 8pt
      value: 8
    - name: 14pt
      value: 14
    - name: 20pt
      value: 20
      flags: 2
    - name: 60pt
      value: 60
    - name: 100pt
      value: 100
  - name: Width
    tag: wdth
    values:
    - name: UltraCondensed
      value: 50
    - name: ExtraCondensed
      value: 62.5
    - name: Condensed
      value: 75
    - name: SemiCondensed
      value: 87.5
    - name: Normal
      value: 100
      flags: 2
    - name: SemiExpanded
      value: 112.5
    - name: Expanded
      value: 125
    - name: ExtraExpanded
      value: 150
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  RobotoSerif-Italic[GRAD,opsz,wdth,wght].ttf:
  - name: Grade
    tag: GRAD
    values:
    - name: G100
      value: 100
      flags: 2
  - name: Optical Size
    tag: opsz
    values:
    - name: 8pt
      value: 8
    - name: 14pt
      value: 14
    - name: 20pt
      value: 20
      flags: 2
    - name: 60pt
      value: 60
    - name: 100pt
      value: 100
  - name: Width
    tag: wdth
    values:
    - name: UltraCondensed
      value: 50
    - name: ExtraCondensed
      value: 62.5
    - name: Condensed
      value: 75
    - name: SemiCondensed
      value: 87.5
    - name: Normal
      value: 100
      flags: 2
    - name: SemiExpanded
      value: 112.5
    - name: Expanded
      value: 125
    - name: ExtraExpanded
      value: 150
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
 
buildStatic: false
outputDir: "../fonts"
